### ISSUE TITLE
jdk-17+35 crashes with JFileChooser on Win10

### ISSUE THREAD

**Issue by holmM** [adoptium/adoptium-support#395] opened 2021-11-09 14:53 UTC
## Summary

``
## Steps to reproduce

Only in 32 bit!!!
```
public class Java17Test 
  {
  public static void main(String[] args)
    {
    try
      {
      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
      }
    catch (Exception e)
      {
      e.printStackTrace();
      }

    new JTree();
    }
  }
```

## Actual results

 A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_STACK_OVERFLOW (0xc00000fd) at pc=0x7a6a1119, pid=6076, tid=14660

 JRE version: OpenJDK Runtime Environment Temurin-17.0.1+12-202111042339 (17.0.1+12) (build 17.0.1-beta+12-202111042339)
 Java VM: OpenJDK Client VM Temurin-17.0.1+12-202111042339 (17.0.1-beta+12-202111042339, mixed mode, emulated-client, serial gc, windows-x86)
 Problematic frame:
 C  [awt.dll+0xd1119]

## Triaging info

Java version: openjdk version "17.0.1-beta" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12-202111042339 (build 17.0.1-beta+12-202111042339)
OpenJDK Client VM Temurin-17.0.1+12-202111042339 (build 17.0.1-beta+12-202111042339, mixed mode, emulated-client) 
For example, "Ubuntu 18.04 on ARM64" or "Windows 10 2004 on x86-64"
-->

How did you install Java?
Extract zip File

Did it work before?
yes, with Java 8 or Java 17 64 bit

Did you test with other Java versions?
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Temurin-17+35 (build 17+35)
OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode
[hs_err_pid6076.log](https://github.com/adoptium/adoptium-support/files/7505641/hs_err_pid6076.log)
)

**Comment by jerboaa** [comment] 2021-11-09 16:32
Duplicate of https://github.com/adoptium/adoptium-support/issues/385

**Closed by jerboaa** 2021-11-09 16:32 UTC
Labels: bug
