### ISSUE TITLE
Namespace setting not work when to set OutputKeys.CDATA_SECTION_ELEMENTS in xml transform

### ISSUE THREAD

**Issue by swingfly** [adoptium/adoptium-support#578] opened 2022-08-29 09:17 UTC
### Please provide a brief summary of the bug

I try to set CDATA property with namespace to solve the issue https://github.com/adoptium/adoptium-support/issues/529 temporarily as https://docs.oracle.com/javase/8/docs/api/javax/xml/transform/Transformer.html#setOutputProperty-java.lang.String-java.lang.String- :

`transformer.setOutputProperty(OutputKeys.CDATA_SECTION_ELEMENTS, "{http://www.opengis.net/kml/2.2}description");`
But it doesn't work yet.
I found the namespace was always parsed to "//www.opengis.net/kml/2.2" in method setCdataSectionElements of ToStream through debug.
I'm not sure this is another bug of jdk.

This is our namespace setting in package-info.java

```
@XmlSchema(
        namespace = "http://www.opengis.net/kml/2.2",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
)
package coursemap.kml;

import javax.xml.bind.annotation.XmlSchema;
```

### Please provide steps to reproduce where possible

see  https://github.com/adoptium/adoptium-support/issues/529

### Expected Results

```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
   <Document>
      <Style id="123">
         <IconStyle>
            <scale>0.96</scale>
            <Icon>
               <href></href>
            </Icon>
            <hotSpot x="0.5" xunits="fraction" y="-0.25" yunits="fraction" />
         </IconStyle>
      </Style>
      <Style id="124">
         <LineStyle>
            <color>ff0000FF</color>
            <width>5</width>
         </LineStyle>
      </Style>
      <Ignorable />
      <Folder>
         <Placemark id="789">
            <name>test placemark</name>
            <styleUrl>#123</styleUrl>
            <LineString>
               <tessellate>1</tessellate>
               <coordinates>-0.14522,50.837645,0.0 -0.143375,50.83669600000001,0.0</coordinates>
            </LineString>
            <WayPoints>
               <tessellate>1</tessellate>
               <coordinates>-0.14522,50.837645,0.0 -0.143375,50.83669600000001,0.0</coordinates>
            </WayPoints>
         </Placemark>
         <Placemark id="123">
            <name>test placemark</name>
            <description><![CDATA[<es:thumbnail></es:thumbnail><es:details>123<br><p>tttt</p></es:details>]]></description>
            <styleUrl>#123</styleUrl>
            <Point>
               <altitudeMode>clampToGround</altitudeMode>
               <coordinates>-0.14522,50.837645</coordinates>
            </Point>
         </Placemark>
         <Placemark distanceMarker="true" id="345">
            <name>test distancemark</name>
            <description><![CDATA[<es:thumbnail></es:thumbnail><es:details>123</es:details>]]></description>
            <styleUrl>#124</styleUrl>
            <Point>
               <altitudeMode>clampToGround</altitudeMode>
               <coordinates>-0.14522,50.837645</coordinates>
            </Point>
         </Placemark>
      </Folder>
   </Document>
</kml>
```

### Actual Results

```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
   <Document>
      <Style id="123">
         <IconStyle>
            <scale>0.96</scale>
            <Icon>
               <href></href>
            </Icon>
            <hotSpot x="0.5" xunits="fraction" y="-0.25" yunits="fraction" />
         </IconStyle>
      </Style>
      <Style id="124">
         <LineStyle>
            <color>ff0000FF</color>
            <width>5</width>
         </LineStyle>
      </Style>
      <Ignorable />
      <Folder>
         <Placemark id="789">
            <name>test placemark</name>
            <styleUrl>#123</styleUrl>
            <LineString>
               <tessellate>1</tessellate>
               <coordinates>-0.14522,50.837645,0.0 -0.143375,50.83669600000001,0.0</coordinates>
            </LineString>
            <WayPoints>
               <tessellate>1</tessellate>
               <coordinates>-0.14522,50.837645,0.0 -0.143375,50.83669600000001,0.0</coordinates>
            </WayPoints>
         </Placemark>
         <Placemark id="123">
            <name>test placemark</name>
            <description>&lt;es:thumbnail&gt;&lt;/es:thumbnail&gt;&lt;es:details&gt;123&lt;br&gt;&lt;p&gt;tttt&lt;/p&gt;&lt;/es:details&gt;</description>
            <styleUrl>#123</styleUrl>
            <Point>
               <altitudeMode>clampToGround</altitudeMode>
               <coordinates>-0.14522,50.837645</coordinates>
            </Point>
         </Placemark>
         <Placemark distanceMarker="true" id="345">
            <name>test distancemark</name>
            <description>&lt;es:thumbnail&gt;&lt;/es:thumbnail&gt;&lt;es:details&gt;123&lt;/es:details&gt;</description>
            <styleUrl>#124</styleUrl>
            <Point>
               <altitudeMode>clampToGround</altitudeMode>
               <coordinates>-0.14522,50.837645</coordinates>
            </Point>
         </Placemark>
      </Folder>
   </Document>
</kml>
```

### What Java Version are you using?

1.8.0.332.b09

### What is your operating system and platform?

Lin

### How did you install Java?

Download pkg from this github.

### Did it work before?

```shell
Yes
```

### Did you test with other Java versions?

```shell
It works well in JDK 1.8.0.322.b06
```

**Comment by swingfly** [comment] 2022-08-29 09:52
It works well after I remove **http://** from namespace.

**Comment by swingfly** [comment] 2022-08-29 09:52
It works well after I remove **http://** from namespace.

**Comment by karianna** [comment] 2022-08-29 19:10
duplicate of #529

**Closed by karianna** 2022-08-29 19:10 UTC
Labels: bug
