### ISSUE TITLE
JFR report uploading failed 

### ISSUE THREAD

**Issue by Sachin1O1** [adoptium/adoptium-support#551] opened 2022-07-29 11:11 UTC
### Please provide a brief summary of the bug

Getting the following error while using JFR in container logs

 ERROR c.m.a.s.profiler.JfrUploadService - Failed to upload file
io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
	at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2113)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)

### Please provide steps to reproduce where possible

Use base image
https://hub.docker.com/layers/eclipse-temurin/library/eclipse-temurin/11-jre/images/sha256-f8971fd7d202674e80743b5591e88bce60f10e02c8f69fcec3776b1b99a5f660?context=explore

### Expected Results

No error

### Actual Results

Failed to upload jfr report

### What Java Version are you using?

openjdk 11

### What is your operating system and platform?

linux/amd64

### How did you install Java?

used base image --> https://hub.docker.com/layers/eclipse-temurin/library/eclipse-temurin/11-jre/images/sha256-f8971fd7d202674e80743b5591e88bce60f10e02c8f69fcec3776b1b99a5f660?context=explore

### Did it work before?

```shell
NA
```

### Did you test with other Java versions?

```shell
Strangely it worked when I use
eclipse-temurin:11-jre-focal
```

**Comment by karianna** [comment] 2022-07-31 10:56
@Sachin1O1 This sounds like a a change with the set of SSL certs that are part of 11.0.16 JRE bundle and/or the O/S.  Are you able to share the certififcate chain you are using (public info only)

**Comment by Sachin1O1** [comment] 2022-08-01 05:19
Can you give me more clarity on the certificate chain that you are asking to share? And moreover, I guess its the issue with the SSL certificates of image itself as I mentioned above it works smoothly on **eclipse-temurin:11-jre-focal** but not on **eclipse-temurin:11-jre**

**Comment by karianna** [comment] 2022-08-01 15:52
Can you try `sudo apt-get install ca-certificates -y` in the container and see if it works after that?

**Comment by Sachin1O1** [comment] 2022-08-02 05:50
Hi @karianna,
 I used the above command in the docker file just after the base image and no lock. Getting same error in logs.
`ERROR c.m.a.s.profiler.JfrUploadService - Failed to upload file
io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
	at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2113)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by johnoliver** [comment] 2022-08-15 17:39
@Sachin1O1 this is caused by https://github.com/netty/netty/issues/12343

Fixing this requires Application Insights bumping the netty dependencies to 4.1.77+, this has already been committed and will go out in the next release.

**Closed** 2022-08-15 19:53 UTC
Labels: bug, help wanted

**Comment by trask** [comment] 2022-08-15 21:24
(@Sachin1O1 if you are able, can you try with the latest Application Insights snapshot build? https://github.com/microsoft/ApplicationInsights-Java/suites/7822243872/artifacts/330538498)
