### ISSUE TITLE
Missing vcruntime140_1.dll

### ISSUE THREAD

**Issue by deh-julien** [adoptium/adoptium-support#307] opened 2021-05-14 09:37 UTC
## Summary

I'm getting the following exception during the initialization of my JavaFX based application causing its crash :
```
java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: C:\****\jre\bin\glass.dll: Can't find dependent libraries
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:288)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:160)
	at javafx.swing/javafx.embed.swing.JFXPanel.lambda$initFx$1(JFXPanel.java:224)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.UnsatisfiedLinkError: C:\****\jre\bin\glass.dll: Can't find dependent libraries
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2648)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:163)
	at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:53)
	at javafx.graphics/com.sun.glass.ui.Application.loadNativeLibrary(Application.java:110)
	at javafx.graphics/com.sun.glass.ui.Application.loadNativeLibrary(Application.java:118)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.access$000(WinApplication.java:39)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication$1.run(WinApplication.java:101)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication$1.run(WinApplication.java:82)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.<clinit>(WinApplication.java:82)
	at javafx.graphics/com.sun.glass.ui.win.WinPlatformFactory.createApplication(WinPlatformFactory.java:39)
	at javafx.graphics/com.sun.glass.ui.win.WinPlatformFactory.createApplication(WinPlatformFactory.java:36)
	at javafx.graphics/com.sun.glass.ui.Application.run(Application.java:144)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:280)
```

Looking at glass.dll dependencies I see that vcruntime140_1.dll is not installed on the targeted system.

## Steps to reproduce

1.  build the following Snippet ([Snippet-missing-dll-vcruntime140_1.zip](https://github.com/adoptium/adoptium-support/files/6477949/Snippet-missing-dll-vcruntime140_1.zip))

MyApp.java:
```
import javafx.stage.*;
import javafx.application.*;
public class MyApp extends Application {
    public static void main(String[] args) {
        System.out.println("Hello from main");
        launch(args);
    }
    @Override
    public void start(Stage stage) {
        System.out.println("Hello from openjfx app");
    }
}
```
pom.xml:
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>Snippet-missing-dll-vcruntime140_1</groupId>
	<artifactId>Snippet-missing-dll-vcruntime140_1</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<dependencies>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-controls</artifactId>
			<version>16</version>
		</dependency>
	</dependencies>
	<build>
		<sourceDirectory>src</sourceDirectory>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<release>11</release>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.openjfx</groupId>
				<artifactId>javafx-maven-plugin</artifactId>
				<version>0.0.6</version>
				<configuration>
					<mainClass>MyApp</mainClass>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

2. Execute with java -jar

## Expected results

The application should run without installing additional software (seems Microsoft Visual C++ 2017 or 2019 provide this lib).

## Actual results

See above

## Triaging info

Java version:
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
**With OpenJFX 16 integrated** (jlink)

What is your operating system and platform?
Windows 10 Enterprise version 1909 on x86-64

How did you install Java?
Binary archive.

Did it work before?
Works if OpenJFX 11.0.2.

Did you test with other Java versions?
No Java11 (LTS) is required.

## Findings / Analysis
AFAIU OpenJFX build has been migrated to VS 2019 since openjfx15 (https://bugs.openjdk.java.net/browse/JDK-8242507), then backported to openjfx11.0.9 (https://bugs.openjdk.java.net/browse/JDK-8252334).
This induced https://bugs.openjdk.java.net/browse/JDK-8242468, fixed in OpenJDK15, but not backported yet to OpenJDK11 (LTS).

**Comment by karianna** [comment] 2022-03-07 15:38
That backport would have to be done upstream.  As we don't ship OpenJFX ourselves it's unlikely that there will be a volunteer from this community.  You may want to ask on the OpenJFX mailing list.

**Comment by JDESTM** [comment] 2022-03-10 07:58
The fix for this issue could be covered by https://bugs.openjdk.java.net/browse/JDK-8282655 (to be confirmed)

**Comment by gdams** [comment] 2022-06-20 16:47
Looks like this was backported to JFX11.0.15 in https://github.com/openjdk/jfx11u/commit/2f2a07a96dc4d739faa63183b4d800e01030b494 - Closing

**Closed by gdams** 2022-06-20 16:47 UTC
Labels: bug, jbs:needs-report, jbs:needs-backport-to-11
