### ISSUE TITLE
eclipse-temurin 11.0.17_8-jdk seems to have memory issues

### ISSUE THREAD

**Issue by shivpatel1** [adoptium/adoptium-support#685] opened 2023-01-11 12:41 UTC
Since quite some time, we have been using eclipse-temurin:11.0.15_10-jdk which was working well enough.
Few days back, we upgraded our Dockerfile to use eclipse-temurin:11.0.17_8-jdk as base image. And we started noticing that the k8s pod now uses almost 3 times more memory.

We built the spring-boot based microservice using 11.0.15_10-jdk and noticed it using around 800+MB, verified for 15 mins+ continuously.
And then built the same microservice using 11.0.15_8-jdk and noticed it using around 2.4+GB, verified for 15 mins+ continuously.

And this readings were taken multiple times. Can someone let us know what is going wrong here? Any work around or a solution available ? 

We tried 11.0.15_10-jre as well as a base image for our microservice. But it still results into same issue of higher memory consumption, with mere about 200-300 MB less than jdk.

Note: We have Heap memory optimizations done in our deployment. Like,  -XX:MinRAMPercentage=70.0 -XX:MaxRAMPercentage=70.0 which means 70% of the pod allocated memory can be used as Heap memory. Which is 25% by default.

To verify that these RAM percentage related configurations are not broken in newer patch, we configured it with 25% only while deploying the image having 11.0.15 JDK. But still the memory consumption was around 800-900MB only.

**Comment by jerboaa** [comment] 2023-01-11 13:25
Please have a look at: https://bugs.openjdk.org/browse/JDK-8281181 and related discussion here:
https://mail.openjdk.org/pipermail/hotspot-runtime-dev/2022-December/059239.html (you might need to subscribe to post there).

If `-XX:+UseContainerCpuShares` fixes your issue then the backport of JDK-8281181 to `11.0.17` is the cause of your issue.

**Comment by shivpatel1** [comment] 2023-01-12 07:42
Thank you very much @jerboaa  . This seems to be working. We will let you know if we will find any side effects of using this parameter.  One thing we noticed is the increase in frequency of garbage collection with 11.0.17_8 along with the solution you suggested.  Also, please let us know if you are already aware of some.

**Comment by jerboaa** [comment] 2023-01-12 09:29
> Thank you very much @jerboaa . This seems to be working.

In theory, `-XX:+UseContainerCpuShares` shouldn't be necessary on kubernetes *iff* you specify proper cpu limits for your containers as described in:
https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/

In that case, the cpu quota mechanism kicks in.

On Kubernetes, cpu shares-based throttling shouldn't come into effect unless there is *no* container cpu limit in place (verify with `-Xlog:os+container=trace` what the OpenJDK container detection code is doing). I suggest to specify container memory and cpu limits via your deployment config (or use defaults via a LimitRange).

See also:
https://bugs.openjdk.org/browse/JDK-8281571 (Problem section)
https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/

**Comment by shivpatel1** [comment] 2023-01-12 09:37
@jerboaa  : We do have defined CPU and memory requests for our k8s containers. Due to functional reasons, we are not limiting the resources for few containers. And yes, the parameter says it is relative to CPU but somehow it actually resolves the memory consumption issue which we were facing with 11.0.17_8. So, there is not an option of setting CPU limit, which makes the suggested parameter is the only option as of now.

**Comment by jerboaa** [comment] 2023-01-12 13:26
The value returned by `Runtime.getRuntime().availableProcessors()` is used in many thread pool impls and running a container on a node (host) with, say 190 cores, and no cpu limits - kubernetes will set a cpu shares value of 2 - will make a huge difference in terms of threads. On 11.0.16 and earlier it would use a single core for such a setup and `190` for `11.0.17` and better. Thread stacks use memory.

I suggest to use `-Xlog:os+container=trace` option to debug this case. It's likely that you'd want to set cpu requests to `2` (cpus) and you should not see the issue anymore with `11.0.17` and also not needing the option.

**Comment by shivpatel1** [comment] 2023-01-13 04:43
@jerboaa  : Thank you for more insights. Setting up cpu requests is not helping much, it still uses twice the memory it uses in 11.0.15. We tried multiple options (0.5, 1, 2). But yes, setting the limit surely makes the difference and memory consumption stays the same as 11.0.15.
Setting the cpu limits for back end services is kind of a big decision for our environment, considering some functional use cases. So, if the first solution is not having any drawbacks, we may go with that as of now.

**Comment by jerboaa** [comment] 2023-01-13 12:36
> So, if the first solution is not having any drawbacks, we may go with that as of now.

The drawback is that you don't know what you're running :-) Is the JVM using 1 core? Likely, if you don't set any cpu limits on your k8s container and use that flag: (remember the default is to set cpu shares to 2 on k8s without any other cpu limits => JVM maps that to a single core). Using that flag in that case is the same as limiting CPU to 1 core and *not* set the flag.

**Comment by jerboaa** [comment] 2023-01-13 12:37
I'm closing this issue. Feel free to reopen if you disagree.

**Closed by jerboaa** 2023-01-13 12:37 UTC
