### ISSUE TITLE
NetBeans 12 LTS does not start with the GTK theme. Linux 64bit over Wayland.

### ISSUE THREAD

**Issue by IGuerreschi** [adoptium/adoptium-support#343] opened 2021-08-13 14:15 UTC
## Summary
NetBeans 12 LTS crashes during startup with the GTK theme.

## Steps to reproduce
Application launch via launcher or script.

## Expected results
Starting the NetBeans 12 LTS application with the GTK theme.

## Actual results
The program crashes and creates an hs_err file.
With the Metal theme it works.
[hs_err_pid3521.log](https://github.com/adoptium/adoptium-support/files/6982987/hs_err_pid3521.log)

## Triaging info

Java version:
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)

What is your operating system and platform?
Fedora Linux 34 on x86-64

How did you install Java?
Downloaded from adoptium and untarred the jdk.

Did it work before?
Yes with AdoptOpenJDK-11.0.11+9

Did you test with other Java versions?
It works on:
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

**Comment by IGuerreschi** [comment] 2021-08-16 15:28
It works with the Fedora java-11-openjdk package
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment 18.9 (build 11.0.12+7)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7, mixed mode, sharing)

Works with sapmachine-jdk-11.0.12
openjdk 11.0.12 2021-07-20 LTS
OpenJDK Runtime Environment SapMachine (build 11.0.12+7-LTS-sapmachine)
OpenJDK 64-Bit Server VM SapMachine (build 11.0.12+7-LTS-sapmachine, mixed mode)

It does not work with Temurin-11.0.12+7
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)

And it doesn't work with AdoptOpenJDK-11.0.11 + 9 which I thought worked
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

**Comment by jerboaa** [comment] 2021-08-16 15:42
Right. This is a duplicate of #335 (or upstream https://bugs.openjdk.java.net/browse/JDK-8255790).

**Closed by jerboaa** 2021-08-16 15:42 UTC
Labels: bug
