### ISSUE TITLE
Random Crash with Log

### ISSUE THREAD

**Issue by Steddo** [adoptium/adoptium-support#625] opened 2022-11-06 04:37 UTC
### Please provide a brief summary of the bug

Minecraft simply crashes. This only happens when I play; it doesn't crash in my long overnight AFK sessions.

Here is one of the crash logs:
[hs_err_pid21168.log](https://github.com/adoptium/adoptium-support/files/9945155/hs_err_pid21168.log)

Also, I don't play vanilla minecraft. I'm playing modded minecraft with fabric. I somewhat suspect a mod in this list to be causing the issue (most recently added .jar files are at the top)
![mods](https://user-images.githubusercontent.com/70127921/200154709-88123503-a2d0-4701-98a4-ba359b44480e.png)

### Please provide steps to reproduce where possible

I could not reproduce it intentionally. It happens at random.

### Expected Results

Minecraft plays without crashing.

### Actual Results

Minecraft crashes randomly.

### What Java Version are you using?

openjdk 17.0.4.1 2022-08-12
OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)

### What is your operating system and platform?

Windows 10 Home
Version 21H2
OS Build 19044.2130

### How did you install Java?

Using OpenJDK17U-jdk_x64_windows_hotspot_17.0.4.1_1.msi

### Did it work before?

No.

### Did you test with other Java versions?

Yes, I have tried:
- jdk-17.0.4.1_windows-x64_bin.exe (installer)
- jre-8u341-windows-x64.exe (installer)

### Relevant log output

_See attached at the top_

Any help is appreciated. I rarely report problems with software, but this one is bugging me because I risk having my long time-lapse recordings get corrupted and cut mid-way. If I'm in the wrong place, a pointer to the right place would also help. Thanks!

**Comment by karianna** [comment] 2022-11-06 14:02
Duplicate of #624

**Closed by karianna** 2022-11-06 14:02 UTC
Labels: bug
