### ISSUE TITLE
Crashes on world load in, FTB StoneBlock 3 1.5.0

### ISSUE THREAD

**Issue by Rainfolly** [adoptium/adoptium-support#666] opened 2022-12-22 00:21 UTC
### Please provide a brief summary of the bug

"A fatal error has been detectd by the Java Runtime Enviroment:
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at" etc.

Just updated the mod pack and wanted to continue on my old world, loaded it up and it crashes. Tried to make a new world also crashes. Tried making a new instance and it as well crashes.

### Expected Results

To load into the game normally

### Actual Results

Game crashes on world load in.

### What Java Version are you using?

no clue

### What is your operating system and platform?

Windows 10 64 bit

**Comment by TommysShinebox** [comment] 2022-12-23 01:00
SAME!

# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff960199db7, pid=7948, tid=19012
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.2+8 (17.0.2+8) (build 17.0.2+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (17.0.2+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x2d9db7]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues

**Comment by DarkDon** [comment] 2022-12-23 01:23
**SAME !**

**Comment by cconnyy** [comment] 2022-12-24 02:54
exact same happening to me

**Comment by Kaishi24** [comment] 2022-12-24 18:16
I'm having the same issue

**Comment by EpicGazel** [comment] 2022-12-25 12:13
The issues disappears when the kube/js suite of mods is removed, that is:
- ftb-stoneblock-companion-0.6.7+mc1.18.2.jar
- kube-utils-forge-0.1.3+mc1.18.2.jar
- kubejs-blood-magic-1802.1.2-build.4.jar
- kubejs-create-forge-1802.2.2-build.28.jar
- kubejs-forge-1802.5.5-build.562.jar
- kubejs-immersive-engineering-1802.2.1-build.35.jar
- kubejs-mekanism-1802.1.3-build.8.jar
- kubejs-thermal-1802.1.5-build.16.jar
- kubejs-tinkers-1802.1.0-build.1.jar
- kubejs-ui-forge-1802.1.8-build.17.jar
- ponderjs-1.18.2-1.1.8.jar

I imagine this issue may be due to one of the recipes tweaks as of 1.5.0:
- Added recipes for Rich Soil turning into Rich Soil Farmland when tilled in a Botany Pot. [#2161](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2161)
- Fixed some recipes there was using sulfur only instead of yellow dye.
- Fixed Tinkers recipe for wires have wrong cost.

**Comment by MrAuslander** [comment] 2022-12-25 21:18
Same Here again. All usual tricks tested and nothing ... Trying @EpicGazel methode now.

**Comment by Talidorn** [comment] 2022-12-26 04:36
If you are running on AMD...


Open configs -> flywheel-client.toml

change:

backend = "INSTANCING"
to
backend = "OFF"

**Comment by EpicGazel** [comment] 2022-12-26 07:18
@Talidorn method fixed it for me. On a rx 5700 so yes, AMD gpu.

> If you are running on AMD...
> 
> Open configs -> flywheel-client.toml
> 
> change:
> 
> backend = "INSTANCING" to backend = "OFF"

**Comment by MrAuslander** [comment] 2022-12-26 13:15
Running on AMD RADEON VEGA 64   @Talidorn confirmed, working for me too. Thank you, good job.

**Comment by DarkDon** [comment] 2022-12-26 18:54
> If you are running on AMD...
> 
> Open configs -> flywheel-client.toml
> 
> change:
> 
> backend = "INSTANCING" to backend = "OFF"

THIS SOLVED THE ISSUE BIG THX !!!

**Comment by ibrudiiv** [comment] 2022-12-27 07:56
> If you are running on AMD...
> 
> Open configs -> flywheel-client.toml
> 
> change:
> 
> backend = "INSTANCING" to backend = "OFF"

6900 XT, this worked as well. Thank you!

**Comment by TommysShinebox** [comment] 2022-12-28 04:09
> If you are running on AMD...
> 
> Open configs -> flywheel-client.toml
> 
> change:
> 
> backend = "INSTANCING" to backend = "OFF"

WORKS!

**Comment by karianna** [comment] 2022-12-28 06:26
Closing this issue as it is not a core JVM concern

**Closed by karianna** 2022-12-28 06:26 UTC
Labels: bug

**Comment by Snowman-25** [comment] 2022-12-29 15:35
> 6900 XT, this worked as well. Thank you!

Same for 7900 XTX

**Comment by JustTrashh** [comment] 2023-01-02 21:40
> If you are running on AMD...
> 
> Open configs -> flywheel-client.toml
> 
> change:
> 
> backend = "INSTANCING" to backend = "OFF"

thx bro

**Comment by nightshade231** [comment] 2023-01-02 23:27
Works on 6700XT

> If you are running on AMD...
> 
> Open configs -> flywheel-client.toml
> 
> change:
> 
> backend = "INSTANCING" to backend = "OFF"

**Comment by TheMath123** [comment] 2023-01-12 23:00
> Se você estiver rodando em AMD...
> 
> Abra as configurações -> flywheel-client.toml
> 
> mudança:
> 
> backend = "INSTANCING" para backend = "OFF"

I did the procedure, and it worked for me. AMD Raedon RX 550 4GB Video Card.
Thank you so much, I'm your fan!!
