### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment inside docker riscv64

### ISSUE THREAD

**Issue by jershell** [adoptium/adoptium-support#697] opened 2023-01-24 21:55 UTC
Error inside riscv64 docker container. on host javac works.

```
./jdk/bin/java --version
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x0000003f78361a88, pid=18, tid=19
#
# JRE version:  (19.0.2) (build )
# Java VM: OpenJDK 64-Bit Server VM (19.0.2-internal-adhoc.jershell.jdk19u, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-riscv64)
# Problematic frame:
# v  ~BufferBlob::native signature handlers 0x0000003f78361a88
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /mnt/jdk/build/linux-riscv64-server-release/images/core.18)
#
# An error report file with more information is saved as:
# /mnt/jdk/build/linux-riscv64-server-release/images/hs_err_pid18.log
#
[hs_err_pid18.log](https://github.com/adoptium/adoptium-support/files/10494230/hs_err_pid18.log)
[hs_err_pid26.log](https://github.com/adoptium/adoptium-support/files/10494231/hs_err_pid26.log)

#
Aborted (core dumped)
```

javac

```
javac --version
#
# A fatal error has been detected by the Java Runtime Environment:
#
# SIGILL (0x4) at pc=0x0000003f8c390a60, pid=21, tid=22
#
# JRE version: OpenJDK Runtime Environment (19.0.1+10) (build 19.0.1+10-Ubuntu-1)
# Java VM: OpenJDK 64-Bit Server VM (19.0.1+10-Ubuntu-1, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-riscv64)
# Problematic frame:
# v ~BufferBlob::vtable chunks 0x0000003f8c390a60
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /root/core.21)
#
# An error report file with more information is saved as:
# /root/hs_err_pid21.log
#
# If you would like to submit a bug report, please visit:
# Unknown
#
```

### Please provide steps to reproduce where possible

Its tested on docker 20.10.12 & 20.10.23

In first i tried use jdk from packages and had this error.

```
FROM ubuntu:22.10
# OR FROM ubuntu:22.04
# OR FROM riscv64/debian:unstable

# java 19
RUN apt-get --quiet update \
&& apt-get --quiet --yes upgrade \
&& apt-get --quiet --yes install ca-certificates-java git curl unzip wget apt-utils tar unzip build-essential \
&& apt-get --quiet --yes install vim-common \
&& apt-get --quiet update && apt-get --quiet --yes install openjdk-19-jdk
``` 

Second attempt 
1. use clear docker riscv64/ubuntu image 
2. and download riscv64 jdk from adoptium or build from source. 
3. enter java --version or javac --version

You have Error.

I tested 
**19.0.1+10 
19.0.2+7 
jdk-20+31**
each does failure
```
### Expected Results

java print version

### Actual Results

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x0000003f78361a88, pid=18, tid=19
#
# JRE version:  (19.0.2) (build )
# Java VM: OpenJDK 64-Bit Server VM (19.0.2-internal-adhoc.jershell.jdk19u, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-riscv64)
# Problematic frame:
# v  ~BufferBlob::native signature handlers 0x0000003f78361a88
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /mnt/jdk/build/linux-riscv64-server-release/images/core.18)
#
# An error report file with more information is saved as:
# /mnt/jdk/build/linux-riscv64-server-release/images/hs_err_pid18.log
#
#
Aborted (core dumped)
```

### What Java Version are you using?

JRE version:  (19.0.2) (build )

### What is your operating system and platform?

Host ubuntu 22.04. 
Docker images based ubuntu 20.04, ubuntu 22.04, debian.

### How did you install Java?
i used 
build from source or download from jenkins or download from github releases or nightbuilds

### Did it work before?

no

### Did you test with other Java versions?
[hs_err_pid18.log](https://github.com/adoptium/adoptium-support/files/10494333/hs_err_pid18.log)
[hs_err_pid26.log](https://github.com/adoptium/adoptium-support/files/10494334/hs_err_pid26.log)

19.0.2 and jdk-20+31

**Comment by sxa** [comment] 2023-02-16 12:31
FYI a [Temurin dev build](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk19u/job/jdk19u-linux-riscv64-temurin/lastSuccessfulBuild/artifact/workspace/target/OpenJDK19U-jre_riscv64_linux_hotspot_2023-01-26-16-13.tar.gz) is ok for me on Ubuntu 22.04 with `docker.io` package `20.10.12-0ubuntu4` with the `riscv64/ubuntu` image (ID: `8b55084b9c02`) with only `curl` and `libatomic1` added, but if I install the Ubuntu JDK19 with all it's prerequisite packages I start getting crashes with both of them which suggests that something in the prerequisites that Ubuntu has is probably breaking things.
```
root@2d3b7abb2ad4:/# jdk-19.0.2+7-jre/bin/java -version
openjdk version "19.0.2-beta" 2023-01-17
OpenJDK Runtime Environment Temurin-19.0.2+7-202301261615 (build 19.0.2-beta+7-202301261615)
OpenJDK 64-Bit Server VM Temurin-19.0.2+7-202301261615 (build 19.0.2-beta+7-202301261615, mixed mode, sharing)
root@2d3b7abb2ad4:/# 
```

**Comment by jershell** [comment] 2023-02-16 14:33
> FYI a [Temurin dev build](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk19u/job/jdk19u-linux-riscv64-temurin/lastSuccessfulBuild/artifact/workspace/target/OpenJDK19U-jre_riscv64_linux_hotspot_2023-01-26-16-13.tar.gz) is ok for me on Ubuntu 22.04 with `docker.io` package `20.10.12-0ubuntu4` with the `riscv64/ubuntu` image (ID: `8b55084b9c02`) with only `curl` and `libatomic1` added, but if I install the Ubuntu JDK19 with all it's prerequisite packages I start getting crashes with both of them which suggests that something in the prerequisites that Ubuntu has is probably breaking things.
> 
> ```
> root@2d3b7abb2ad4:/# jdk-19.0.2+7-jre/bin/java -version
> openjdk version "19.0.2-beta" 2023-01-17
> OpenJDK Runtime Environment Temurin-19.0.2+7-202301261615 (build 19.0.2-beta+7-202301261615)
> OpenJDK 64-Bit Server VM Temurin-19.0.2+7-202301261615 (build 19.0.2-beta+7-202301261615, mixed mode, sharing)
> root@2d3b7abb2ad4:/# 
> ```

I tested it. Its true only for JRE. JDK not working.

Do you can reproduce with JDK?

Its my Dockerfile with libatomic1 & curl

```docker
FROM riscv64/ubuntu:22.04

WORKDIR /root
RUN apt update && apt upgrade -yq && apt install curl libatomic1 -yq
RUN curl -O https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk19u/job/jdk19u-linux-riscv64-temurin/lastSuccessfulBuild/artifact/workspace/target/OpenJDK19U-jdk_riscv64_linux_hotspot_2023-01-26-16-13.tar.gz
RUN tar -xvf ./OpenJDK19U-jdk_riscv64_linux_hotspot_2023-01-26-16-13.tar.gz -C /opt
ENV JAVA_HOME="/opt/jdk-19.0.2+7"
ENV PATH="${PATH}:${JAVA_HOME}/bin"
RUN java --version
RUN javac --version
RUN rm ./OpenJDK19U-jdk_riscv64_linux_hotspot_2023-01-26-16-13.tar.gz

```
docker build -t riscv64-ubuntu-java-foo-bar .

My output.
```
Removing intermediate container b663ffca26db
 ---> 6e2f7a76dbd8
Step 6/10 : ENV JAVA_HOME="/opt/jdk-19.0.2+7"
 ---> Running in b5e339e013c5
Removing intermediate container b5e339e013c5
 ---> da14a276f4d9
Step 7/10 : ENV PATH="${PATH}:${JAVA_HOME}/bin"
 ---> Running in 1c59643c0054
Removing intermediate container 1c59643c0054
 ---> c545661abe61
Step 8/10 : RUN java --version
 ---> Running in 15a7bcbcb596
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x0000003f943e9a88, pid=7, tid=8
#
# JRE version:  (19.0.2+7) (build )
# Java VM: OpenJDK 64-Bit Server VM (19.0.2-beta+7-202301261615, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-riscv64)
# Problematic frame:
# v  ~BufferBlob::native signature handlers 0x0000003f943e9a88
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /root/core.7)
#
# An error report file with more information is saved as:
# /root/hs_err_pid7.log
#
#
Aborted (core dumped)
The command '/bin/sh -c java --version' returned a non-zero code: 134


```

**Comment by sxa** [comment] 2023-02-16 14:57
I may have just got lucky with my earlier test - I tried again with the JRE and in the same container it crashed the first time, worked the next two, then failed again :-(

**Comment by jershell** [comment] 2023-03-21 14:29
JRE version:  20.0+36. The same error.

```sh
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x0000003fa4204a42, pid=6, tid=7
#
# JRE version:  (20.0+36) (build )
# Java VM: OpenJDK 64-Bit Server VM (20-beta+36-202303091259, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-riscv64)
# Problematic frame:
# v  ~BufferBlob::native signature handlers 0x0000003fa4204a42
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /root/core.6)
#
# An error report file with more information is saved as:
# /root/hs_err_pid6.log
[0.319s][warning][os] Loading hsdis library failed
#
#
```

**Comment by luhenry** [comment] 2023-06-21 09:57
I couldn't reproduce on QEMU. Trying to reproduce on an HiFive Unmatched board.

**Comment by luhenry** [comment] 2023-06-21 10:40
Issue is to do with I/D cache coherency. On Unmatched boards (which doesn't have Instruction and Data cache coherency), the call to [`__builtin___clear_cache `](https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html#index-_005f_005fbuiltin_005f_005f_005fclear_005fcache) which translates to the syscall `riscv_flush_icache` fails due to `EPERM` when run in Docker. I'm currently running in Docker with `--privileged` to verify the issue is exactly that. 

Next steps are:
- Fix in OpenJDK to test whether `__builtin___clear_cache` works as expected, and exit VM accordingly with a log message.
- Fix in Linux Kernel to make sure icache flush works as expected in a docker container. (Working internally at Rivos to get that fixed or figure out whether there is a fix already.)

**Comment by luhenry** [comment] 2023-06-21 12:21
Latest update: the issue seems to be in Docker in the end and it has been [fixed in later versions](https://github.com/moby/moby/commit/4c2f18f6cca5a89c1e0828a18f01e90ac40fc9b9). Now, another problem is to get a build of docker with that fix on Ubuntu 22.04 and later.

The workaround is to run docker with `--security-opt seccomp=unconfined` or to specifically allow the `riscv_flush_icache` syscall similarly to https://github.com/moby/moby/commit/4c2f18f6cca5a89c1e0828a18f01e90ac40fc9b9.

I think we can close this issue.

**Closed** 2023-06-21 21:57 UTC
Labels: bug

**Comment by sxa** [comment] 2023-06-22 17:55
Confirmed on my LPi4A in a Fedora container that the `--security-opt seccomp=unconfined` option seems to resolve the problem.

**Comment by luhenry** [comment] 2023-07-17 08:31
We've added a test in OpenJDK at startup: https://github.com/openjdk/jdk/pull/14670. If the test fails (aka, riscv_flush_icache isn't available), it will print an informative error message and refuse the boot the JVM (which would crash a short time afterwards anyway).
