### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by RangerRick** [adoptium/adoptium-support#454] opened 2022-02-14 17:40 UTC
## Summary

It appears the SSL certificate has expired. I'm getting SSL errors downloading both Debian and RPM packgaes.

## Steps to reproduce

(example on Debian Buster:)

```
apt update
apt -y install apt-transport-https ca-certificates gnupg2 wget
wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | apt-key add -
echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" > /etc/apt/sources.list.d/adoptium.list
apt update
apt -y install temurin-11-jdk
```

## Expected results

Temurin JDK 11 installs.

## Actual results

```
#5 6.591 --2022-02-14 17:33:52--  https://packages.adoptium.net/artifactory/api/gpg/key/public
#5 6.598 Resolving packages.adoptium.net (packages.adoptium.net)... 34.139.10.89
#5 6.634 Connecting to packages.adoptium.net (packages.adoptium.net)|34.139.10.89|:443... Warning: apt-key output should not be parsed (stdout is not a terminal)
#5 6.661 connected.
#5 6.718 ERROR: The certificate of 'packages.adoptium.net' is not trusted.
#5 6.718 ERROR: The certificate of 'packages.adoptium.net' doesn't have a known issuer.
#5 6.718 gpg: no valid OpenPGP data found.
```

## Triaging info

Java version: N/A

What is your operating system and platform?

Debian GNU/Linux 10 (buster)

How did you install Java?

can't

Did it work before?

yes

**Comment by karianna** [comment] 2022-02-14 17:46
known issues with JFrog, we're on with their support team

**Comment by gdams** [comment] 2022-02-15 12:35
closing as duplicate of https://github.com/adoptium/installer/issues/434

**Closed by gdams** 2022-02-15 12:35 UTC
Labels: bug

**Comment by Xisikka** [comment] 2023-10-12 18:40
still seeing this issue recently
