### ISSUE TITLE
Processing crashes when trying to open or save a file

### ISSUE THREAD

**Issue by IvanFLeon** [adoptium/adoptium-support#339] opened 2021-08-09 16:29 UTC
## Summary

Processing 4 beta 1 is using OpenJDK 11.0.12, but it crashes when some dialog shows up. Dialogs like the ones that open when trying to save or open a file.

## Triaging info

Java version:

OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)

What is your operating system and platform?

Archlinux on x86-64

How did you install Java?

It comes with Processing.

## Report log
```
---------------  S U M M A R Y ------------
    20
    21 Command Line: -Djna.nosys=true -Djava.library.path=lib:modes/java/libraries/javafx/library/linux64 --module-path=modes/java/libraries/javafx/library/linux64/modules --add-modules=javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.media,javafx.swing,       javafx.web -Xmx512m processing.app.ui.Splash
    22
    23 Host: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, 12 cores, 15G, Arch Linux
    24 Time: Mon Aug  9 09:17:13 2021 PDT elapsed time: 14.089794 seconds (0d 0h 0m 14s)
    25
    26 ---------------  T H R E A D  ---------------
    27
    28 Current thread (0x00007f0878b8b000):  JavaThread "ShowDialog" [_thread_in_native, id=2340, stack(0x00007f08471e1000,0x00007f08472e2000)]
    29
    30 Stack: [0x00007f08471e1000,0x00007f08472e2000],  sp=0x00007f08472dd9a8,  free space=1010k
    31 Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
    32 C  0x00007f07f1fb20cc
    33
    34 Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
    35 j  sun.awt.X11.GtkFileDialogPeer.run(Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/io/FilenameFilter;ZII)V+0 java.desktop@11.0.12
    36 j  sun.awt.X11.GtkFileDialogPeer.showNativeDialog()V+156 java.desktop@11.0.12
    37 j  sun.awt.X11.GtkFileDialogPeer.lambda$setVisible$0()V+1 java.desktop@11.0.12
    38 j  sun.awt.X11.GtkFileDialogPeer$$Lambda$415.run()V+4 java.desktop@11.0.12
    39 j  java.lang.Thread.run()V+11 java.base@11.0.12
    40 v  ~StubRoutines::call_stub
    41
    42 siginfo: si_signo: 11 (SIGSEGV), si_code: 2 (SEGV_ACCERR), si_addr: 0x00007f07f1fb20cc
    43
    44 Register to memory mapping:
    45
    46 RAX=0x00007f07f1fb20cc points into unknown readable memory: 00 01 00 00
    47 RBX=0x00007f08000c3f28 points into unknown readable memory: 0x0000000000000000 | 00 00 00 00 00 00 00 00
    48 RCX=0x0 is NULL
    49 RDX=0x0000000100000036 is pointing into metadata
    50 RSP=0x00007f08472dd9a8 is pointing into the stack for thread: 0x00007f0878b8b000
    51 RBP=0x00007f08472dd9b0 is pointing into the stack for thread: 0x00007f0878b8b000
    52 RSI=0x0000000066766172 is an unknown value
    53 RDI=0x00007f08000c40b0 points into unknown readable memory: 0x0000000000000001 | 01 00 00 00 00 00 00 00
    54 R8 =0x00007f08d5e9d860: <offset 0x000000000001f860> in /home/ivanleon/Software/Processing/processing-4.0b1/java/lib/libharfbuzz.so at 0x00007f08d5e7e000
    55 R9 =0x00007f0800000080 points into unknown readable memory: 0x00007f0800179fe0 | e0 9f 17 00 08 7f 00 00
    56 R10=0x00007f08000c40f0 points into unknown readable memory: 0x0000000000000000 | 00 00 00 00 00 00 00 00
    57 R11=0x0 is NULL
    58 R12=0x0 is NULL
    59 R13=0x00007f08d5d290c0: <offset 0x000000000009e0c0> in /usr/lib/libharfbuzz.so.0 at 0x00007f08d5c8b000
    60 R14=0x00007f08472dd9c0 is pointing into the stack for thread: 0x00007f0878b8b000
    61 R15=0x00007f08000bc050 points into unknown readable memory: 0x00007f08000a8a60 | 60 8a 0a 00 08 7f 00 00
```

**Comment by jerboaa** [comment] 2021-08-09 16:34
This is a duplicate of #335.

**Closed by jerboaa** 2021-08-09 16:34 UTC
Labels: bug
