### ISSUE TITLE
Font issue noticed moving from JDK 11 to JDK 17

### ISSUE THREAD

**Issue by tellison** [adoptium/adoptium-support#367] opened 2021-09-23 09:18 UTC
JDK11:
![スクリーンショット 2021-09-23 033212](https://user-images.githubusercontent.com/8847851/134402061-6eca2db0-725c-4173-9379-5a66c12a6212.jpg)
![スクリーンショット 2021-09-23 033248](https://user-images.githubusercontent.com/8847851/134402063-3276feda-2419-4810-8289-de235f4d0c76.jpg)
JDK17:
![スクリーンショット 2021-09-23 033427](https://user-images.githubusercontent.com/8847851/134402055-aa241b55-648e-46a4-907e-21c7a711024c.jpg)
![スクリーンショット 2021-09-23 033455](https://user-images.githubusercontent.com/8847851/134402059-4136d6b1-754c-4da4-9198-153921c9dcb3.jpg)
I have upgraded JDK11(LTS) to JDK17(LTS), but with my java app, it makes turns out japanese font into chinese japanese font.
Is this issue (to make in this repository)?
Anyway thank you for your effort too.

_Originally posted by @roflsunriz in https://github.com/adoptium/adoptium/issues/74#issuecomment-925177125_

**Comment by tellison** [comment] 2021-09-23 09:22
@roflsunriz Thank you for reporting this problem. Please can you help us track down what is happening by providing more information?

## Triaging info

Java version:
_Paste the entire output of java -version._

What is your operating system and platform?
_For example, "Ubuntu 18.04 on ARM64" or "Windows 10 2004 on x86-64"_

How did you install Java?
_Whether you used a binary archive (zip, tar.gz), an installer package (MSI, rpm,
etc.), a version manager (jabba, jenv, etc.)._

Did it work before?
_If so, please specify what changed._

Did you test with other Java versions?
_Please specify exactly what Java versions you tested with, for example by
pasting the output of java -version.

If available, test with an upstream build:

* https://adoptopenjdk.net/upstream.html (8, 11)
* http://jdk.java.net/ (anything newer than 8, 11)_

Anything else you think is relevant here?

**Comment by roflsunriz** [comment] 2021-09-23 09:34
Java version:
JDK11:
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)
JDK17:
jdk-17+35

What is your operating system and platform?
Microsoft Windows 10 Pro
10.0.19043 N/A Build 19043
Version 21H1 (OS build 19043)

How did you install Java?
MSI

Did it work before?
When I upgraded to JDK17, font changed. But if i roll back to JDK11, font turns back to normal.

Did you test with other Java versions?
_Please specify exactly what Java versions you tested with, for example by
pasting the output of java -version.

If available, test with an upstream build:

    https://adoptopenjdk.net/upstream.html (8, 11)
    http://jdk.java.net/ (anything newer than 8, 11)_

Anything else you think is relevant here?
Been using adoptium's JDK but this font problem is first time to me for JDK17.

**Comment by roflsunriz** [comment] 2021-09-23 09:48
Did you test with other Java versions?
Tested with
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.302-b08, mixed mode)

Recompiled with JDK8, it worked with normal font.

**Comment by tellison** [comment] 2021-09-23 12:32
@takiguc are you able to have a look at this issue?

**Comment by takiguc** [comment] 2021-09-23 15:04
@tellison OK, I'll check this issue.

**Comment by takiguc** [comment] 2021-09-26 16:51
@roflsunriz 
Hello.
Sorry I'm late.
I tried to run NicoCacheGUI Ver0.09 with
* Windows 10 Pro 21H1 (19043.1110) Japanese edition
* JDK17 (Temurin-17+35) via installer

I could not recreate this issue.
I checked your screen shot, it seemed your Windows might not be Japanese edition because Weather information was English.
I'd like to clarify your system again.
Also please run following commands with JDK17.
And show me the outputs.
```
java -XshowSettings:properties -version 2>&1 | findstr user
java -XshowSettings:properties -version 2>&1 | findstr encoding
```

**Comment by roflsunriz** [comment] 2021-09-26 19:08
Sorry I forgot and didn't tell you that I have changed system setting Japanese to English.
I'm not running <b>NicoCacheGUI v0.09</b> - it is implemented with NicoCache <b>natively</b> so i'm running itself rathar than external GUI.
java -XshowSettings:properties -version 2>&1 | findstr user
    user.country = US
    user.dir = C:\Users\user name
    user.home = C:\Users\user name
    user.language = en
    user.name = user name
    user.script =
    user.variant =
java -XshowSettings:properties -version 2>&1 | findstr encoding
    file.encoding = Cp1252
    native.encoding = Cp1252
    sun.io.unicode.encoding = UnicodeLittle
    sun.jnu.encoding = MS932

**Comment by takiguc** [comment] 2021-09-27 16:42
Thanks @roflsunriz 

It seemed this situation happened by JDK12.
I assume this issue was related by

**Comment by takiguc** [comment] 2021-09-27 17:11
Hello @roflsunriz 

It seemed this issue happened by JDK12.
I could not determine which code change affected this issue.
But maybe, 
[JDK-8185496](https://bugs.openjdk.java.net/browse/JDK-8185496) Improve performance of system properties initialization in initPhase1
[JDK-8213424](https://bugs.openjdk.java.net/browse/JDK-8213424) VersionProps duplicate and skipped initialization

It's related WIndows MUI (Multilingual User Interface).
For workaround, please add "-Dfile.encoding=MS932" into java command option on startup script.

**Comment by roflsunriz** [comment] 2021-09-27 22:08
Thank you for suggesting workaround. But is this issue will be fixed soon? Or is it going to be abandoned?

**Comment by smlambert** [comment] 2021-09-28 13:37
Based on @takiguc's investigation ( thank you @takiguc ! ), this issue will need to be reported upstream to the OpenJDK project and the answer to your question, will it be fixed/abandoned will depend on how the issue is prioritized in the upstream project.

**Comment by tellison** [comment] 2021-10-12 08:34
@takiguc thank you for the analysis. As Severin wrote, please report upstream, and add a link to the conversation here for reference. We will watch that conversation, and action this issue accordingly.

**Comment by takiguc** [comment] 2021-12-16 14:12
Hello @roflsunriz .
Sorry I'm late.

[JDK-8275145](https://bugs.openjdk.java.net/browse/JDK-8275145) was backported to jdk17.0.2 by [JDK-8275379](https://bugs.openjdk.java.net/browse/JDK-8275379).

I verified this issue with Adoptium following jdk17u Nightly build.
https://github.com/adoptium/temurin17-binaries/releases/download/jdk17u-2021-12-15-10-13-beta/OpenJDK17U-jdk_x64_windows_hotspot_2021-12-15-10-13.zip

I confirmed the fix was merged into jdk17.0.2.

Hello @tellison .
Please let me know if I need to do something.

**Closed** 2022-11-22 20:42 UTC
Labels: jbs:needs-report
